blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogPageView.as_view(), name='blogpage'),
    path('<slug:slug>/', views.BlogPostView.as_view(), name='blogpost'),
    path('tag/<str:tag>/', views.TagPageView.as_view(), name='tagpage'),
]

wagtailblog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import re_path, include

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

# view 404 in development, remove in production
from django.views.defaults import page_not_found


# view 404 in development, remove in production
def custom_page_not_found(request):
    return page_not_found(request, None)


urlpatterns = [
    re_path(r'^django-admin/', admin.site.urls),
    re_path(r'^admin/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^search/$', search_views.search, name='search'),
    re_path(r'^blog/', include('blog.urls')),

    # view 404 in development, remove in production
    re_path(r'^404/$', custom_page_not_found),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    re_path(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wagtailblog/templates/base.html
{% load wagtailcore_tags %}
{% load static wagtailuserbar %}

<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="{% block description %}{% endblock %}" />
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>
        {% block title %}
            {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
        {% endblock %}
        {% block title_suffix %}
            | {{ website_name }}
        {% endblock %}
    </title>

    {# Global stylesheets #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% comment %}<link rel="icon" href="{% static '../media/favicon/favicon.ico' %}" />{% endcomment %}
    <link rel="icon" href="{{ website_favicon }}" />
    <noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>

    {% block extra_css %}
        {# Override this in templates to add extra stylesheets #}
    {% endblock %}
  </head>
  <body>
    {# provides a contextual flyout menu for logged-in users #}
    {% wagtailuserbar 'bottom-left' %}

    <!-- Wrapper -->
    <div id="wrapper">

    <!-- Header -->
    {% block header %}
    <header id="header">
      <div class="inner">
          <!-- Logo -->
          <a href="/" class="logo top">
            <span class="symbol"><img src="{{ website_logo.file.url }}" alt="{{ website_logo.title }}" /></span><span class="title">{{ website_name }}</span>
          </a>
        <!-- Nav -->
        <nav>
          <ul>
            <li><a href="#menu">Menu</a></li>
          </ul>
        </nav>
      </div>
    </header>
    {% endblock %}

    <!-- Menu -->
    {% block menu %}
    <nav id="menu">
      <!-- Search box -->
      <form action="{% url 'search' %}" method="get" class="top">
        <input class="icon" type="text" placeholder="&#61442;" name="q"{% if search_query %} value="{{ search_query }}"{% endif %}/>
        <!--<input type="submit" value="Search" class="button">-->
      </form>
      <h2>Meny</h2>
      <ul>
        <li><a href="/">Hem</a></li>
        <li><a href="{% url 'blog:blogpage' %}">Blogg</a></li>
      </ul>
    </nav>
    {% endblock %}

    <!-- Main -->
    {% block content %}
      {# Override this in templates to add the content of the page #}
    {% endblock %}

    <!-- Footer -->
    <footer id="footer">
      <div class="inner">
        <section>
          <h2>Om {{ website_name }}</h2>
            {{ website_footer|richtext }}
        </section>
        <section>
          <h2>Följ på Instagram</h2>
          <ul class="icons">
            <li><a href="{{ website_instagram }}" class="icon style2 shrink fa fa-instagram fa-2x"><span class="label">Instagram</span></a></li>
          </ul>
        </section>
        <ul class="copyright">
          <li><i class="fa fa-copyright fa-lg" aria-hidden="true"></i> <span id="copyright">{{ website_name }}</span></li>
        </ul>
      </div>
    </footer>

    </div>

    {# Global javascript #}
    <script src="{% static 'js/breakpoints.min.js' %}"></script>
    <script src="{% static 'js/browser.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/util.js' %}"></script>

    {% block extra_js %}
        {# Override this in templates to add extra javascript #}
    {% endblock %}
  </body>
</html>