blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogPageView.as_view(), name='blogpage'),
    path('<slug:slug>/', views.BlogPostView.as_view(), name='blogpost'),
    path('tag/<str:tag>/', views.TagPageView.as_view(), name='tagpage'),
]

blog/models.py
import re

from django import forms
from django.db import models
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from wagtail.search import index
from wagtail.core.fields import RichTextField
from wagtail.core.models import Page, Orderable
from wagtail.snippets.models import register_snippet
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel, MultiFieldPanel, HelpPanel

from taggit.models import TaggedItemBase
from modelcluster.fields import ParentalKey
from modelcluster.contrib.taggit import ClusterTaggableManager


class BlogPostTag(TaggedItemBase):
    """Tags for blog posts"""
    content_object = ParentalKey(
        'BlogPost',
        related_name='blog_post_tag',
        on_delete=models.CASCADE
    )


class BlogPostKeyword(TaggedItemBase):
    """Meta keywords for posts"""
    content_object = ParentalKey(
        'BlogPost',
        related_name='blog_post_keyword',
        on_delete=models.CASCADE
    )


class BlogPageKeyword(TaggedItemBase):
    """Meta keywords for the blog index page"""
    content_object = ParentalKey(
        'BlogPage',
        related_name='blog_page_keyword',
        on_delete=models.CASCADE
    )


class BlogPage(Page):
    """Model for the blog index page"""

    # For the header on the blogpage.
    header_text = RichTextField(blank=True, null=True)
    header_image = models.ForeignKey(
        'wagtailimages.Image',
        blank=False,
        null=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    # HTML meta tags for the blogpage.
    description = models.CharField(max_length=160, blank=True, null=True)
    keywords = ClusterTaggableManager(
        through=BlogPageKeyword,
        related_name='blog_page_keyword',
        blank=True
    )

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('header_text', classname="full"),
            ImageChooserPanel('header_image'),
        ], heading="Header"),
        MultiFieldPanel([
            HelpPanel(template='help_panel/metatag_help.html'),
            FieldPanel('keywords', classname="full"),
            FieldPanel('description', classname="full"),
        ], heading="HTML meta tags"),
    ]


class BlogPost(Page):
    """Model for blog posts"""

    # Main blog post content and information.
    intro = models.CharField(max_length=150, blank=True, null=True)
    date = models.DateTimeField("Post date")
    text = RichTextField(blank=True)
    tags = ClusterTaggableManager(
        through=BlogPostTag,
        related_name='blog_post_tag',
        blank=True
    )

    # Show or hide the gallery.
    show = models.BooleanField(null=True)

    # HTML meta tags for the specific blog post.
    description = models.CharField(max_length=160, blank=True, null=True)
    keywords = ClusterTaggableManager(
        through=BlogPostKeyword,
        related_name='blog_post_keyword',
        blank=True
    )

    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('text'),
    ]

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            HelpPanel(template='help_panel/content_help.html'),
            FieldPanel('intro'),
            FieldPanel('date'),
            FieldPanel('tags'),
            FieldPanel('text'),
        ], heading="Content"),
        MultiFieldPanel([
            HelpPanel(template='help_panel/gallery_help.html'),
            FieldPanel('show', widget=forms.CheckboxInput),
            InlinePanel('gallery_images', label="Gallery images"),
        ], heading="Gallery"),
        MultiFieldPanel([
            HelpPanel(template='help_panel/metatag_help.html'),
            FieldPanel('keywords', classname="full"),
            FieldPanel('description', classname="full"),
        ], heading="HTML meta tags"),
    ]

    def intro_text(self):
        """Return intro text for the tiles"""
        if self.intro:
            return self.intro + "..."
        else:
            # If no intro, remove HTML and return the 150 first character
            # of the posts text as intro instead.
            return re.sub("<[^>]*>", "", self.text[:300])[:150] + "..."

    def featured_image(self):
        """Give posts a feature image."""
        gallery_item = self.gallery_images.first()
        if gallery_item:
            return gallery_item.image
        else:
            return None

    def next_post(self):
        """Return the next blog post."""
        posts = self.get_siblings().live().filter(
            blogpost__date__lte=timezone.now()).order_by('-blogpost__date')
        next = None
        for post in posts:
            if post.title == self.title:
                return next
            next = post
        return None

    def previous_post(self):
        """Return the previous blog post."""
        posts = self.get_siblings().live().filter(
            blogpost__date__lte=timezone.now()).order_by('blogpost__date')
        previous = None
        for post in posts:
            if post.title == self.title:
                return previous
            previous = post
        return None


class BlogPostGalleryImage(Orderable):
    """Image gallery feature for posts"""
    page = ParentalKey(
        BlogPost,
        on_delete=models.CASCADE,
        related_name='gallery_images'
    )
    image = models.ForeignKey(
        'wagtailimages.Image',
        on_delete=models.CASCADE,
        related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        ImageChooserPanel('image'),
        FieldPanel('caption'),
    ]

blog/views.py
import re
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from wagtail.core.models import Page

from .models import BlogPage, BlogPost
from home.models import HomePage


class BlogPageView(ListView):
    model = BlogPost
    template_name = 'blog/blog_page.html'
    paginate_by = 12

    def get_queryset(self):
        return BlogPost.objects.live().filter(
            date__lte=timezone.now()).order_by("-date")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['keywords'] = BlogPage.objects.first().keywords.all()
        context['description'] = BlogPage.objects.first().description
        context['title'] = BlogPage.objects.first().title
        context['header_image'] = BlogPage.objects.first().header_image.file.url
        context['header_text'] = BlogPage.objects.first().header_text
        context['object'] = Page.objects.get(slug='blog')
        return context


class BlogPostView(DetailView):
    model = BlogPost
    template_name = 'blog/blog_post.html'

    def get_queryset(self):
        return BlogPost.objects.live().filter(
            date__lte=timezone.now()).order_by("-date")


class TagPageView(ListView):
    model = BlogPost
    template_name = 'blog/tag_page.html'
    paginate_by = 12

    def get_queryset(self):
        return BlogPost.objects.live().filter(
            tags__name__iexact=self.kwargs['tag'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_tag'] = self.unslugify(self.kwargs['tag'])
        context['all_tags'] = BlogPost.tags.all()
        return context

    def unslugify(self, slug):
        """Convert slug to string."""
        return re.sub('-', ' ', slug)

blog/templates/blog/blog_page.html
{% extends "base.html" %}
{% load wagtailcore_tags  %}
{% load wagtailimages_tags %}

{% block description %}{% if description %}{{ description }}{% endif %}{% endblock %}
{% block keywords %}{{ keywords|join:", " }}{% endblock %}

{% block title %}
  {% if object.seo_title %}
    {{ object.seo_title }}
  {% else %}
    {{ object.title }}
  {% endif %}
{% endblock %}

{% block content %}
<header id="headerimage" style="background-image: url('{{ header_image }}');">
  <div class="inner">
    <h1 id="pageheader">{{ title }}</h1>
    {{ header_text|richtext }}
  </div>
</header>
  <div id="main">
    <div class="inner">
      <div class="tiles">
        {% for post in object_list %}
        <article class="style1">
          <span class="image">
          {% if post.specific.featured_image %}
            {% image post.specific.featured_image fill-353x326 %}
          {% else %}
            <img src="{{ default_preview }}" alt="default" width="353" height="326">
          {% endif %}
          </span>
          <a href="{% url 'blog:blogpost' post.specific.slug %}">
            <h3>{{ post.specific.title }}</h3>
            <div class="content">
              <p>{{ post.specific.intro_text }}</p>
            </div>
          </a>
        </article>
        {% endfor %}
      </div>
      {% if is_paginated %}
      <div class="pagination">
        {% if page_obj.has_previous %}
        <div id="pagination_previous"><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i> Nyare inlägg</a></div>
        {% endif %}
        {% if page_obj.has_next %}
        <div id="pagination_next"><a href="?page={{ page_obj.next_page_number }}">Äldre inlägg <i class='fa fa-angle-right'></i></a></div>
        {% endif %}
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

blog/templates/blog/blog_post.html
{% extends "base.html" %}
{% load static %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}

{% block description %}{% if object.description %}{{ object.description }}{% endif %}{% endblock %}
{% block keywords %}{{ object.keywords.all|join:", " }}{% endblock %}

{% block title %}
  {% if object.seo_title %}
    {{ object.seo_title }}
  {% else %}
    {{ object.title }}
  {% endif %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/gallery.css' %}">
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/gallery.js' %}"></script>
{% endblock %}

{% block content %}
        <header>
          {% if object.featured_image %}
            {% image object.featured_image fill-1920x540 as header %}
            <img src="{{ header.url }}" alt="{{ header.alt }}" style="width: 100%;">
            {% else %}
            <img src="{{ default_feature }}" alt="default" style="width: 100%;">
          {% endif %}
        </header>
        <div id="main">
          <div class="inner">
            <h1>{{ object.title }}</h1>
            <div class="date">
              <p class="meta">{{ object.date.date }}
                {% if object.first_published_at.date != object.last_published_at.date %}
                <i>(Uppdaterad: {{ object.last_published_at.date }})</i>
                {% endif %}
              </p>
            </div>
            <div class="content">
              {{ object.text|richtext }}

              {% if object.show %}
              <!--Lightbox gallery-->
              <div class="gallery">
                <!-- Images used to open the lightbox -->
                <div class="row">
                  {% for img in object.gallery_images.all %}
                  <div class="column">
                    {% image img.image fill-320x240 as item %}
                    <img src="{{ item.url }}" alt="{{ item.alt }}" onclick="openModal();currentSlide({{ forloop.counter }})" class="hover-shadow">
                  </div>
                  {% endfor %}
                </div>
                <!-- The Modal/Lightbox -->
                <div id="myModal" class="modal">
                  <div class="modal-content">

                    {% for gallery in object.gallery_images.all %}
                    <div class="mySlides">
                      <div class="numbertext">{{ forloop.counter }} / {{ object.gallery_images.all|length }}</div>
                      {% image gallery.image width-1080 as photo %}
                      {% if photo.height > photo.width or photo.height == photo.width %}
                      <img src="{{ photo.url }}" alt="{{ photo.alt }}" style="width:45%; display: block; margin-left:auto; margin-right:auto;">
                      {% else %}
                      <img src="{{ photo.url }}" alt="{{ photo.alt }}" style="width:100%">
                      {% endif %}
                      <p class="caption">{{ gallery.caption }}</p>
                    </div>
                    {% endfor %}

                    <!--Close button-->
                    <span class="close cursor" onclick="closeModal()"><i class="fa fa-times" aria-hidden="true"></i></span>
                    <!-- Next/previous controls -->
                    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                    <a class="next" onclick="plusSlides(1)">&#10095;</a>

                  </div>
                </div>
              </div>
              {% endif %}

            </div>

          {% if object.tags.all.count %}
          <div class="tags blogpost">

              {% for tag in object.tags.all %}
                  <a href="{% url 'blog:tagpage' tag|slugify %}">#{{ tag }}</a>
              {% endfor %}

          </div>
          {% endif %}

          {% if object.next_post %}
            <div id="next"><a href="{% url 'blog:blogpost' object.next_post.slug %}"><i class="fa fa-angle-left"></i> Nyare inlägg</a></div>
          {% endif %}
          {% if object.previous_post %}
            <div id="previous"><a href="{% url 'blog:blogpost' object.previous_post.slug %}">Äldre inlägg <i class="fa fa-angle-right"></i></a></div>
          {% endif %}
          </div>
        </div>
{% endblock %}

blog/templates/blog/tag_page.html
{% extends "base.html" %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}

{% block title %}{{ current_tag }}{% endblock %}

{% block description %}Inlägg taggade med '{{ current_tag }}' på {{ website_name }}{% endblock %}

{% block keywords %}{{ current_tag }}{% endblock %}

{% block content %}
<div id="main">
  <div class="inner tag">
    <h1>Inlägg taggade med "{{ current_tag }}"</h1>
    <div class="tiles">
      {% for post in object_list %}
      <article class="style1">
        <span class="image">
        {% if post.specific.featured_image %}
          {% image post.specific.featured_image fill-353x326 %}
        {% else %}
          <img src="{{ default_preview }}" alt="default" width="353" height="326">
        {% endif %}
        </span>
        <a href="{% url 'blog:blogpost' post.slug %}">
          <h3>{{ post.specific.title }}</h3>
          <div class="content">
            <p>{{ post.specific.intro_text }}</p>
          </div>
        </a>
      </article>
      {% empty %}
        <p id="empty">Hittade tyvärr inga taggade inlägg. Testa någon av taggarna nedanför istället.</p>
          <div class="tags">
              {% for tag in all_tags %}
                <a href="{% url 'blog:tagpage' tag|slugify %}">#{{ tag }}</a>
              {% endfor %}
          </div>
      {% endfor %}
    </div>
    {% if is_paginated %}
    <div class="pagination">
      {% if page_obj.has_previous %}
      <div id="pagination_previous"><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i> Nyare inlägg</a></div>
      {% endif %}
      {% if page_obj.has_next %}
      <div id="pagination_next"><a href="?page={{ page_obj.next_page_number }}">Äldre inlägg <i class='fa fa-angle-right'></i></a></div>
      {% endif %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}